DEFINE_COMPUTER(THINKPAD)
DEFINE_COMPUTER(DESKTOP)
DEFINE_COMPUTER(ENG106)
DEFINE_COMPUTER(UNI_TEACHING)
DEFINE_COMPUTER(UNI_RESEARCH)
DEFINE_COMPUTER(DREAMHOST)

DEFINE_GROUP(PERSONAL,    THINKPAD|DESKTOP)
DEFINE_GROUP(USES_DEBIAN, THINKPAD|DESKTOP)
